// This file is generated by Astro DB
declare module 'astro:db' {
	export const Comment: import("@astrojs/db/runtime").Table<
		"Comment",
		{"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Comment","primaryKey":false,"optional":false}},"authorId":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"authorId","collection":"Comment","primaryKey":false,"optional":false,"references":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Author","primaryKey":true}}}},"body":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"body","collection":"Comment","primaryKey":false,"optional":false}},"likes":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"likes","collection":"Comment","primaryKey":false,"optional":false}},"flagged":{"type":"boolean","schema":{"optional":false,"unique":false,"deprecated":false,"name":"flagged","collection":"Comment"}},"published":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"published","collection":"Comment"}},"metadata":{"type":"json","schema":{"optional":false,"unique":false,"deprecated":false,"name":"metadata","collection":"Comment"}}}
	>;
	export const Author: import("@astrojs/db/runtime").Table<
		"Author",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Author","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Author","primaryKey":false,"optional":false}}}
	>;
}
